### ISSUE TITLE
Poner la dirección en la barra

### ISSUE THREAD

**Issue by nurialeonsallent** [nurialeonsallent/nurialeon.com#1]
- añadir Calle Castillejos 326, 1-1, Barcelona (al principio)
-

**Comment by isc30** [comment]
![image](https://user-images.githubusercontent.com/10807051/158878340-c63cda73-679b-4d6d-95ac-153c5c8857e0.png)
![image](https://user-images.githubusercontent.com/10807051/158878386-e078c3ae-5d21-4a8c-9272-b5e04ab2fab6.png)

**Comment by isc30** [comment]
opcion 2:
![image](https://user-images.githubusercontent.com/10807051/158879310-f605a39b-e125-4a0d-b882-30a41747652c.png)

**Comment by nurialeonsallent** [comment]
añadir simbolo del mapa en blanquito delante de Calle. Además cambiar el 1/1 por 1-1

**Comment by nurialeonsallent** [comment]
![image](https://user-images.githubusercontent.com/66083832/158991593-7ac32e14-53f5-4da5-a9a3-9e83f7faa2ae.png)

**Comment by nurialeonsallent** [comment]
> opcion 2: ![image](https://user-images.githubusercontent.com/10807051/158879471-2c09e858-d0a8-4da2-9e9a-cdf02b5b628e.png)

este me gusta mas
