### ISSUE TITLE
Cambiar estructura pagina inicio

### ISSUE THREAD

**Issue by nurialeonsallent** [nurialeonsallent/nurialeon.com#2]
Poner columna derecha debajo (como en el movil) y centrar
![image](https://user-images.githubusercontent.com/66083832/158842551-fb667400-14de-4909-a778-8d9419da955a.png)

**Comment by nurialeonsallent** [comment]
más margenes, la web más centrada.

**Comment by nurialeonsallent** [comment]
COSAS IMPORTANTES DE LA WEB:

- WEB SIMPLE PERO DIRECTA, SIN DEMASIADA INFORMACION, SOLO INFO RELEVANTE
- DISEÑO EQUILIBRADO Y PROFESIONAL
- CONTENIDO DE CALIDAD (poco a poco iré haciendo más posts, pidiendo más reseñas)

**Comment by isc30** [comment]
![image](https://user-images.githubusercontent.com/10807051/175552649-1378caf8-822a-4734-8832-90d784dfe114.png)

**Comment by isc30** [comment]
![image](https://user-images.githubusercontent.com/10807051/175553016-23ed9226-9821-4630-b277-f62cca3715b8.png)

**Comment by isc30** [comment]
final design
![image](https://user-images.githubusercontent.com/10807051/183285177-46e8da65-40e9-478f-ba55-c41ad9aaa73c.png)
