### ISSUE TITLE
Cambiar redes movil

### ISSUE THREAD

**Issue by isc30** [nurialeonsallent/nurialeon.com#3]
![image](https://user-images.githubusercontent.com/10807051/158877721-a88722fe-75e2-4d04-92b7-07a97482410b.png)

**Comment by nurialeonsallent** [comment]
mejor si. Y si ponemos primero NURIA LEON PSICOLOGA y despues la foto a bajo y despues redes?

**Comment by nurialeonsallent** [comment]
![image](https://user-images.githubusercontent.com/66083832/158992249-a970a82d-bf5a-411c-9744-03d3ec685180.png)

**Comment by isc30** [comment]
![image](https://user-images.githubusercontent.com/10807051/159162159-6073a7ee-917a-4388-b2eb-055baa33def3.png)
foto 150px
