### ISSUE TITLE
contacto - resumen

### ISSUE THREAD

**Issue by nurialeonsallent** [nurialeonsallent/nurialeon.com#4]
![image](https://user-images.githubusercontent.com/66083832/158992505-02791d57-0f1a-442c-8a42-78947f245a30.png)

**Comment by nurialeonsallent** [comment]
abajo de la pagina por ejemplo, o justo en la sección de contacto, encima del mapa algo asi? como lo ves?

**Comment by isc30** [comment]
2 columnas, contenido actual en la columna izquierda y el nuevo en la
derecha, en el movil aparece primero la direccion

color granate de fondo?

--
[image: Ivan Sanz-Carasa] Ivan Sanz-Carasa
***@***.***
+34 670 096 753
