### ISSUE TITLE
mover valoraciones de sitio

### ISSUE THREAD

**Issue by nurialeonsallent** [nurialeonsallent/nurialeon.com#6]
![image](https://user-images.githubusercontent.com/66083832/158993937-86c8afa7-5a29-42bc-aa69-e99fceee7643.png)

Tampoco lo veo mal asi

**Comment by isc30** [comment]
si podemos evitar scroll horizontal mejor, podemos estilizar las que hay y darle un aspecto mas individual a cada review (lo mismo que la foto pero en vertical)
